{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"HospitalER\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.141.1451.0 (25.03)+5007b7650f7edbed506e31fcb76584cd6d711788"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "en-IN",
    "tables": [
      {
        "name": "HospitalER",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "lineageTag": "a1b2c3d4-e5f6-4g5h-6i7j-8k9l0m1n",
            "sourceColumn": "date",
            "summarizeBy": "none"
          },
          {
            "name": "patient_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a2b3c4d5-e6f7-4g7h-6i8j-8k9l0m1n",
            "sourceColumn": "patient_id",
            "summarizeBy": "none"
          },
          {
            "name": "patient_gender",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a3b4c5d6-e7f8-4g8h-6i9j-8k9l0m1n",
            "sourceColumn": "patient_gender",
            "summarizeBy": "none"
          },
          {
            "name": "patient_age",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "lineageTag": "a4b5c6d7-e8f9-4g9h-6iaj-8k9l0m1n",
            "sourceColumn": "patient_age",
            "summarizeBy": "none"
          },
          {
            "name": "patient_sat_score",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "lineageTag": "a5b6c7d8-e9f0-4ga1-6hbj-8k9l0m1n",
            "sourceColumn": "patient_sat_score",
            "summarizeBy": "none"
          },
          {
            "name": "patient_first_inital",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a6b7c8d9-e0f1-4ga2-6hbj-8k9l0m1n",
            "sourceColumn": "patient_first_inital",
            "summarizeBy": "none"
          },
          {
            "name": "patient_last_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a7b8c9d0-e1f2-4ga3-6hbj-8k9l0m1n",
            "sourceColumn": "patient_last_name",
            "summarizeBy": "none"
          },
          {
            "name": "patient_race",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a8b9c0d1-e2f3-4ga4-6hbj-8k9l0m1n",
            "sourceColumn": "patient_race",
            "summarizeBy": "none"
          },
          {
            "name": "patient_admin_flag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a9b0c1d2-e3f4-4ga5-6hbj-8k9l0m1n",
            "sourceColumn": "patient_admin_flag",
            "summarizeBy": "none"
          },
          {
            "name": "patient_waittime",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "lineageTag": "aa1b2c3d-e4f5-4ga6-6hbj-8k9l0m1n",
            "sourceColumn": "patient_waittime",
            "summarizeBy": "none"
          },
          {
            "name": "department_referral",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ab2c3d4e-f5g6-4ga7-6hbj-8k9l0m1n",
            "sourceColumn": "department_referral",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "a1b2c3d4-e5f6-4g5h-6i7j-8k9l0m1n",
        "measures": [
          {
            "name": "Total Revenue",
            "expression": "SUM(HospitalER[Revenue])",
            "formatString": "0",
            "lineageTag": "a2b3c4d5-e6f7-4g7h-6i8j-8k9l0m1n"
          },
          {
            "name": "Average Discount",
            "expression": "AVG(HospitalER[Discount])",
            "formatString": "0",
            "lineageTag": "a3b4c5d6-e7f8-4g8h-6i9j-8k9l0m1n"
          },
          {
            "name": "Total Orders",
            "expression": "COUNT(HospitalER[OrderID])",
            "formatString": "0",
            "lineageTag": "a4b5c6d7-e8f9-4g9h-6iaj-8k9l0m1n"
          }
        ],
        "partitions": [
          {
            "name": "HospitalER",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Databases(\"health-careserver.database.windows.net\"),",
                "    #\"HospitalER\" = Source{[Name=\"HospitalER\"]}[Data],",
                "    dbo_HospitalER = #\"HospitalER\"{[Schema=\"dbo\",Item=\"HospitalER\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(dbo_HospitalER,{{\"date\", type dateTime}, {\"patient_id\", type text}, {\"patient_gender\", type text}, {\"patient_age\", int64.Type}, {\"patient_sat_score\", int64.Type}, {\"patient_first_inital\", type text}, {\"patient_last_name\", type text}, {\"patient_race\", type text}, {\"patient_admin_flag\", type text}, {\"patient_waittime\", int64.Type}, {\"department_referral\", type text}}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Changed Type\", each ([Gender] <> \"Persons\") and ([Location] <> \"Location\"))",
                "in",
                "    #\"Filtered Rows\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}
